name: DEPLOY

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_KEY }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p ${{ secrets.REMOTE_PORT }} -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy base.site
        run: |
          rsync -azv --delete \
            --exclude-from="deploy/exclude.txt" \
            -e "ssh -p ${{ secrets.REMOTE_PORT }}" \
            base.site/ \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/jk135.site/

      - name: Deploy collector.site
        run: |
          rsync -azv --delete \
            --exclude-from="deploy/exclude.txt" \
            -e "ssh -p ${{ secrets.REMOTE_PORT }}" \
            collector.site/ \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/collector.jk135.site/

      - name: Deploy reporting.site
        run: |
          rsync -azv --delete \
            --exclude-from="deploy/exclude.txt" \
            -e "ssh -p ${{ secrets.REMOTE_PORT }}" \
            reporting.site/ \
            ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/reporting.jk135.site/
